export const DataMusic = {
  meta: {
    channelId: "UC-9-kyTW8ZkZNDHQJ6FgpwQ",
    title: "Musique",
    description:
      "Explorez la chaîne YouTube Music pour découvrir les talents, les sélections d'artistes et les playlists du jour. Abonnez-vous pour profiter des toutes dernières nouveautés musicales.\nCette chaîne a été générée automatiquement par le système de détection vidéo de YouTube.",
    avatar: [
      {
        url: "//yt3.googleusercontent.com/vCqmJ7cdUYpvR0bqLpWIe8ktaor4QafQLlfQyTuZy-M9W_YafT8Wo9kdsKL2St1BrkMRpVSJgA=s88-c-k-c0x00ffffff-no-rj-mo",
        width: 88,
        height: 88,
      },
      {
        url: "//yt3.googleusercontent.com/vCqmJ7cdUYpvR0bqLpWIe8ktaor4QafQLlfQyTuZy-M9W_YafT8Wo9kdsKL2St1BrkMRpVSJgA=s176-c-k-c0x00ffffff-no-rj-mo",
        width: 176,
        height: 176,
      },
    ],
    subscriberCountText: "119 M",
    subscriberCount: null,
    keywords: null,
    isFamilySafe: true,
    availableCountries: [
      "MO",
      "LB",
      "HU",
      "CA",
      "BO",
      "GM",
      "IS",
      "TL",
      "HM",
      "AQ",
      "NL",
      "FM",
      "NP",
      "RS",
      "LV",
      "BY",
      "PH",
      "SJ",
      "MG",
      "GN",
      "FK",
      "NE",
      "UY",
      "AT",
      "BB",
      "RW",
      "MT",
      "SK",
      "TM",
      "MF",
      "WF",
      "ER",
      "NF",
      "BL",
      "DE",
      "DM",
      "HN",
      "AD",
      "BJ",
      "MZ",
      "PA",
      "TN",
      "KP",
      "AM",
      "TR",
      "CF",
      "TT",
      "CV",
      "IE",
      "SV",
      "SC",
      "AZ",
      "IT",
      "CX",
      "TF",
      "CM",
      "KM",
      "ML",
      "FI",
      "MV",
      "NO",
      "SB",
      "BR",
      "LU",
      "NZ",
      "ST",
      "SD",
      "CY",
      "AO",
      "PR",
      "MK",
      "DO",
      "MQ",
      "MW",
      "AF",
      "MC",
      "ZW",
      "BG",
      "DJ",
      "GI",
      "MX",
      "NA",
      "TW",
      "SL",
      "BM",
      "TV",
      "PW",
      "AX",
      "BA",
      "TG",
      "VN",
      "PF",
      "KI",
      "TZ",
      "US",
      "AI",
      "BD",
      "RU",
      "MM",
      "PS",
      "AW",
      "GY",
      "IO",
      "SA",
      "RO",
      "SS",
      "JP",
      "BH",
      "ES",
      "GU",
      "GB",
      "VA",
      "SZ",
      "CG",
      "BQ",
      "CO",
      "KG",
      "KW",
      "AR",
      "MS",
      "GD",
      "HK",
      "ZA",
      "CU",
      "CC",
      "LC",
      "PY",
      "IL",
      "LA",
      "ET",
      "JE",
      "FR",
      "MR",
      "GT",
      "SX",
      "RE",
      "MH",
      "BT",
      "GH",
      "MP",
      "SI",
      "UM",
      "MU",
      "LI",
      "FO",
      "LS",
      "MN",
      "PT",
      "SO",
      "BI",
      "AL",
      "CL",
      "GR",
      "OM",
      "JM",
      "DK",
      "KZ",
      "TJ",
      "BN",
      "LY",
      "GQ",
      "PL",
      "CK",
      "CD",
      "BE",
      "TC",
      "MD",
      "HR",
      "QA",
      "VC",
      "LR",
      "WS",
      "CI",
      "CZ",
      "UG",
      "IR",
      "FJ",
      "ID",
      "EG",
      "GW",
      "BS",
      "HT",
      "JO",
      "KR",
      "SH",
      "KE",
      "NG",
      "TO",
      "PN",
      "TH",
      "SM",
      "MA",
      "PK",
      "AU",
      "EE",
      "AS",
      "BV",
      "IN",
      "BZ",
      "NR",
      "UZ",
      "GF",
      "AG",
      "TD",
      "CN",
      "BW",
      "CR",
      "LT",
      "VI",
      "NI",
      "VU",
      "ZM",
      "SN",
      "SY",
      "GL",
      "CW",
      "EH",
      "SE",
      "VG",
      "MY",
      "KH",
      "IQ",
      "GS",
      "PM",
      "PE",
      "ME",
      "UA",
      "BF",
      "YE",
      "LK",
      "NC",
      "DZ",
      "YT",
      "VE",
      "TK",
      "GG",
      "SR",
      "KY",
      "GP",
      "PG",
      "AE",
      "EC",
      "KN",
      "IM",
      "GA",
      "CH",
      "GE",
      "SG",
      "NU",
    ],
    tabs: ["Accueil", "Communauté", "À propos"],
  },
  continuation: "",
  data: [
    {
      type: "playlist_listing",
      title: "Classements",
      subtitle: null,
      data: [
        {
          type: "playlist",
          playlistId: "PL4fGSI1pDJn7bK3y1Hx-qpHBqfr6cesNs",
          title: "Top 100 des titres France",
          subtitle: "YouTube Music Global Charts · Playlist",
          channelId: "UCrKZcyOJVWnJ60zM1XWllNw",
          channelTitle: "YouTube Music Global Charts · Playlist",
          videoCount: "100",
          videoId: "6WrVXWgn094",
          publishedTimeText: "Mise à jour aujourd'hui",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/6WrVXWgn094/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLADX2u3-Ptw2dumDTa4cIa8KxQ_Yg",
              width: 480,
              height: 270,
            },
          ],
        },
        {
          type: "playlist",
          playlistId: "PL4fGSI1pDJn50iCQRUVmgUjOrCggCQ9nR",
          title: "Top 100 des clips musicaux France",
          subtitle: "YouTube Music Global Charts · Playlist",
          channelId: "UCrKZcyOJVWnJ60zM1XWllNw",
          channelTitle: "YouTube Music Global Charts · Playlist",
          videoCount: "100",
          videoId: "6WrVXWgn094",
          publishedTimeText: "Mise à jour aujourd'hui",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/6WrVXWgn094/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLADX2u3-Ptw2dumDTa4cIa8KxQ_Yg",
              width: 480,
              height: 270,
            },
          ],
        },
        {
          type: "playlist",
          playlistId: "PLsa-dEwv56FaoevRy1iSkp2YWt9udgkdJ",
          title: "Les 20 clips tendance France",
          subtitle: "Populaire sur YouTube – France · Playlist",
          channelId: "UCmzy72gDEpfXoFV9Xdtd0DQ",
          channelTitle: "Populaire sur YouTube – France · Playlist",
          videoCount: "20",
          videoId: "6GzmlV3H9mk",
          publishedTimeText: "Mise à jour aujourd'hui",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/6GzmlV3H9mk/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD4F0W0sia7hspLjrgxt7BU1AfNNQ",
              width: 480,
              height: 270,
            },
          ],
        },
        {
          type: "playlist",
          playlistId: "PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i",
          title: "Top 100 des titres dans le monde",
          subtitle: "YouTube Music Global Charts · Playlist",
          channelId: "UCrKZcyOJVWnJ60zM1XWllNw",
          channelTitle: "YouTube Music Global Charts · Playlist",
          videoCount: "99",
          videoId: "BVdngsy95mY",
          publishedTimeText: "Mise à jour aujourd'hui",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/BVdngsy95mY/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBbDrQhUf_UoHmeGbOPvrAAeKCEWg",
              width: 480,
              height: 270,
            },
          ],
        },
        {
          type: "playlist",
          playlistId: "PL4fGSI1pDJn5kI81J1fYWK5eZRl1zJ5kM",
          title: "Top 100 des clips musicaux dans le monde",
          subtitle: "YouTube Music Global Charts · Playlist",
          channelId: "UCrKZcyOJVWnJ60zM1XWllNw",
          channelTitle: "YouTube Music Global Charts · Playlist",
          videoCount: "99",
          videoId: "VBcs8DZxBGc",
          publishedTimeText: "Mise à jour aujourd'hui",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/VBcs8DZxBGc/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAdcfkqd6_Pwc0cImzyT4YJ576ETg",
              width: 480,
              height: 270,
            },
          ],
        },
      ],
    },
    {
      type: "video_listing",
      title: "Nouveaux clips",
      subtitle: null,
      data: [
        {
          type: "video",
          videoId: "yOuqn4w1ozA",
          title: "Selena Gomez - Single Soon (Official Music Video)",
          viewCount: "2850482",
          publishedTimeText: "il y a 12 heures",
          lengthText: "2:57",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/yOuqn4w1ozA/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCx7pzzAobYFvDbMHZcyvBTddRH4Q",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/yOuqn4w1ozA/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBNFFF4TD431kT2Kds7jeRSuu7PmQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/yOuqn4w1ozA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA3cKTVbM4v8otB4Ynnlu3MGOsGeA",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/yOuqn4w1ozA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDB-oO-pW7ihglUINUMQYYMxUjqVQ",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "982hvz5Ax9Y",
          title: "Kery James feat. Kalash - 6 du mat (Clip Officiel)",
          viewCount: "199345",
          publishedTimeText: "il y a 1 jour",
          lengthText: "4:45",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/982hvz5Ax9Y/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLASTaHMnNGavePnypcrCARfMp-9SQ",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/982hvz5Ax9Y/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDKWvwcN_pUK--t4QqmKQ6Bd2nFkQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/982hvz5Ax9Y/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAlDIiockw-Xojhl__nXw6zIFtMgQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/982hvz5Ax9Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZdXqlORngmPTFIV-VopJ2HNTX_g",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "IZ3XMOdOdKM",
          title: "Miley Cyrus - Used To Be Young (Official Video)",
          viewCount: "2363849",
          publishedTimeText: "il y a 12 heures",
          lengthText: "3:22",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/IZ3XMOdOdKM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBhzA-5YPFORmIca7DORxvVn-tgAQ",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/IZ3XMOdOdKM/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAMFTi0U7HnyTsduvwlYom1ym-Qqg",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/IZ3XMOdOdKM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDUWzenFA-HwiWqshL27CIGGglZOw",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/IZ3XMOdOdKM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDUzB-dCvagRHYZUj6vAvmObTiZnA",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "wbfPOw65xXw",
          title: "MHD - Jungle",
          viewCount: "77108",
          publishedTimeText: "il y a 7 heures",
          lengthText: "2:24",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/wbfPOw65xXw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAkbRLXdPXx_RaTQsnHa0U7id-D7Q",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/wbfPOw65xXw/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA5UGTlmqeDugFshCjKfe-T9L1VRQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/wbfPOw65xXw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDTpZemVvQfkWC4J_quEY3RV3r50A",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/wbfPOw65xXw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBD7KOG-k_top30cra0mBOqGrbyJg",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "qgHV_nv8u3E",
          title: "Burna Boy - Cheat On Me feat. Dave",
          viewCount: "942411",
          publishedTimeText: "il y a 3 jours",
          lengthText: "3:46",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/qgHV_nv8u3E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAcGwyw-Y9gVt1EKrAK3ndp78Kd2Q",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/qgHV_nv8u3E/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB-yBn9zi-eOOox824R7D5d7Am8eA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/qgHV_nv8u3E/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDMj-K5bep0TzP5-lik6it7DbtSGA",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/qgHV_nv8u3E/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC2YV6x4zgAE7CyJhOK7qGc8q2U6w",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "CDy_PWi5BCw",
          title: "Kaneki - Blue feat. Naps & Ninho (Clip officiel)",
          viewCount: "725349",
          publishedTimeText: "il y a 4 jours",
          lengthText: "3:08",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/CDy_PWi5BCw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD61NT4HklVyZrYEdbMZBtrpA3mNg",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/CDy_PWi5BCw/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDMGTcaf2KuotUf1rwSVrZmvwuVEQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/CDy_PWi5BCw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC69AWbLxZZ_ELvtnaH2_xqtKOTsw",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/CDy_PWi5BCw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBOZFTIP3_omR7jAPGkr2MWMsX_vQ",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "hhELbo229ek",
          title: "Fally Ipupa - Afsana (Clip Officiel)",
          viewCount: "89951",
          publishedTimeText: "il y a 6 heures",
          lengthText: "4:48",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/hhELbo229ek/hqdefault.jpg?sqp=-oaymwE1CKgBEF5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AH-CYACpAWKAgwIABABGHIgQygsMA8=&rs=AOn4CLCm8j2zuayiFV22bNigE0K142mmzQ",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/hhELbo229ek/hqdefault.jpg?sqp=-oaymwE1CMQBEG5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AH-CYACpAWKAgwIABABGHIgQygsMA8=&rs=AOn4CLBZgr7igOyy6YEbD3LWlrhBsBJbYA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/hhELbo229ek/hqdefault.jpg?sqp=-oaymwE2CPYBEIoBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAqQFigIMCAAQARhyIEMoLDAP&rs=AOn4CLBuBmMvAvHb5V4GtJLUD13CAytmmQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/hhELbo229ek/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAqQFigIMCAAQARhyIEMoLDAP&rs=AOn4CLA4FDa-V0lYoBE_Za5nCReuGl7ZxQ",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "ru1LC9lW20Q",
          title:
            "Ryan Gosling - I'm Just Ken Exclusive (From Barbie The Album) [Official]",
          viewCount: "2595218",
          publishedTimeText: "il y a 4 jours",
          lengthText: "3:52",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/ru1LC9lW20Q/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDOcqbslNEOujPr6wePbK77mOOWkA",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/ru1LC9lW20Q/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDrlq8umk2fRsglUww1zYoPg2J9MQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/ru1LC9lW20Q/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCQDZIFxiZvwteWiVKT8ZyFRFfFCQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/ru1LC9lW20Q/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBB0ZoPDE1mDGeK_k_qwXGR0cVn5A",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "qMNLOTk-y7w",
          title: "Zaho de Sagazan - Dis-moi que tu m'aimes (modular version)",
          viewCount: "9941",
          publishedTimeText: "il y a 1 jour",
          lengthText: "5:33",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/qMNLOTk-y7w/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDfs22YzZHGDJXxTtYEfcSkxodzvg",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/qMNLOTk-y7w/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBwBTwYV1nAEcAd-61x4WolvgtlvQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/qMNLOTk-y7w/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATEr7jtIgdyxVtvHh2tcIg9VVrjQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/qMNLOTk-y7w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfVeikZtRk_9rfJa2kJQ-m_EQZSg",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "Hhr4xECq5Fc",
          title: "YUNGBLUD - Hated (Official Music Video)",
          viewCount: "187626",
          publishedTimeText: "il y a 1 jour",
          lengthText: "3:11",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/Hhr4xECq5Fc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAOUcKM_YF4lLL3_Wl5PD03jQaeUA",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/Hhr4xECq5Fc/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCwzmlm8cP8ekkeg5LXWbQkcOZqZg",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/Hhr4xECq5Fc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAPvZk-tq1yfDr2idMGOTKI7QgxoQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/Hhr4xECq5Fc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC3mks9KXDnTawKR96y73Azm1JRKA",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "7t5V5ygeqLY",
          title: "Iggy Azalea - Money Come [Official Music Video]",
          viewCount: "298979",
          publishedTimeText: "il y a 12 heures",
          lengthText: "2:48",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/7t5V5ygeqLY/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDlRgzTzYSFBKAsXa2V9NxPUNH-_A",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/7t5V5ygeqLY/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCRyZuvknUpavL-ROPLw6Dum8Wo0w",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/7t5V5ygeqLY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBMNhhYBa7_VG99mwcqkImLR8JnXA",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/7t5V5ygeqLY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDcHb833BxbBiF3lAzP-dcGN0z8qQ",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "7ympPwhl0iU",
          title: 'Lauv - "Love U Like That" [Official Video]',
          viewCount: "408555",
          publishedTimeText: "il y a 4 jours",
          lengthText: "3:33",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/7ympPwhl0iU/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDkXVsPx8IUePOCKwHLnXxCjaavCw",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/7ympPwhl0iU/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCOrAZqbcAdCO721_dHjXrmXnZyJA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/7ympPwhl0iU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDrXpMe-GYKyV16sMVBE_aX85rGgQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/7ympPwhl0iU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAdPvHSNq6BMl8Aciw8CPE4vJCx5Q",
              width: 336,
              height: 188,
            },
          ],
        },
      ],
    },
    {
      type: "video_listing",
      title: "Playlist",
      subtitle:
        "En Musique #AvecMoi : Besoin d'une bonne dose de musique ? Voici une sélection de concerts sur-mesure et sons inédits pour vous évader quelques heures.",
      data: [
        {
          type: "video",
          videoId: "DNwg4QvpUaA",
          title: "L.E.J - Summer 2020",
          viewCount: "8747712",
          publishedTimeText: "il y a 2 ans",
          lengthText: "3:02",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/DNwg4QvpUaA/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDPzFDNbtVofMeC0FoB9bUVTEukRQ",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/DNwg4QvpUaA/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBwZrGb-BdwOvJYEw0FCSYSn-E-aw",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/DNwg4QvpUaA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBl4l_XB5CGoe5in7Y7oDr-FgPjbQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/DNwg4QvpUaA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYG0uYiA7fEiKT1V6re_gHNcMdew",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "DurDZkK58VE",
          title:
            "R.E.M. - Live from Glastonbury Festival, 1999 (Complete BBC Broadcast) #AtHome",
          viewCount: "1409002",
          publishedTimeText: "il y a 3 ans",
          lengthText: "1:20:11",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/DurDZkK58VE/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDe3G6YMvLh_5OhbinrzksycBcxYw",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/DurDZkK58VE/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDBOd87KnebA6JMfhAiUEQkGhERbg",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/DurDZkK58VE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAO20mKOceP-sSQswfYKGTbJCYUtg",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/DurDZkK58VE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCGhII9SbOPUD3lhIKr96OOda7ZrA",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "LCt3b5updPQ",
          title: "Clean Bandit x Global Citizen: House Party Against Hunger",
          viewCount: "475773",
          publishedTimeText: "Diffusé il y a 3 ans",
          lengthText: "11:54:56",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/LCt3b5updPQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCJ6fMWUn90PcsiVFzu3y-h74LRRg",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/LCt3b5updPQ/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDXIs-N0Nj-cvdck4GG2l0Is6czmg",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/LCt3b5updPQ/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCKMkRNLPjFi5et7K4tIc58WK3wBg",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/LCt3b5updPQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDiYC8ITs8NfLPdXtmteuwwfeuscw",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "F4DMWTjAGlo",
          title:
            "Heineken and UEFA presents the opening party powered by Defected",
          viewCount: "301036",
          publishedTimeText: "Diffusé il y a 3 ans",
          lengthText: "8:04:11",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/F4DMWTjAGlo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCl_q67oslCtKndYYsnR79lhivGjA",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/F4DMWTjAGlo/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDjtWVmZeCaFH-jJkbZpXzXjN26_g",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/F4DMWTjAGlo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1T9D3ciq332GbgSUmiZD-BnexaQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/F4DMWTjAGlo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBwSmlcon4tccuBlOq5U2fvjsbLow",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "31tClDsYJKY",
          title: "One Direction - 10 Years of One Direction",
          viewCount: "19772173",
          publishedTimeText: "il y a 3 ans",
          lengthText: "4:57",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/31tClDsYJKY/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB7-K4RJyuLogLC_NJP_ZQVF5fV8w",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/31tClDsYJKY/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBILpflkKpxrVo_tsU-H1YWSw9Vaw",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/31tClDsYJKY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB4aSlOyjsIAu_BuqtRDnoc4xOOrQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/31tClDsYJKY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATae4KVd_mtTBaVukWJlbU48ofEQ",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "7kHUp8KNOfE",
          title: "BAD BUNNY – YouTube Artist Spotlight Stories",
          viewCount: "12330661",
          publishedTimeText: "il y a 3 ans",
          lengthText: "10:28",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/7kHUp8KNOfE/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDwQWa67Pb_77pNIAhdV9ALSF7SaQ",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/7kHUp8KNOfE/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD0YxjLdw77z3MzLW2luh8FRLLZsg",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/7kHUp8KNOfE/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA7_KIcok2zNyNoL4lAzwcQrvRZbg",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/7kHUp8KNOfE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDOvpxIF2kBkGlJ3dy61ja8gWfiCQ",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "JRFW6fBfaq0",
          title: "L.E.J - Tous les deux (Live session)",
          viewCount: "281770",
          publishedTimeText: "il y a 3 ans",
          lengthText: "2:36",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/JRFW6fBfaq0/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAr7v4x68sDBB-T6LHNbva9NEobEg",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/JRFW6fBfaq0/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBiwnlhMydREw8tI6tew9IfRmKIww",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/JRFW6fBfaq0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAVLgJ7pI24lg08JZvfcR1DMpAGwQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/JRFW6fBfaq0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCKQopGRlHhnpBHbX1rw2vBWJ0GPg",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "JlOa5gyQf6s",
          title: "Nicky Romero: Another World (Virtual Liveshow)",
          viewCount: "662140",
          publishedTimeText: "Diffusé il y a 3 ans",
          lengthText: "59:03",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/JlOa5gyQf6s/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDk0_1jtKaZ57cnmzGBCPEmWI0TJA",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/JlOa5gyQf6s/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBV3nc7KfNDK-urFwvIqFDtt9y1Vg",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/JlOa5gyQf6s/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBE0iZrccI-DGZiceHtpbKHRNBPgw",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/JlOa5gyQf6s/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCsVTYbI0aXUBCFMlgllG49d7RFhQ",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "VnMMmFinROU",
          title: "Calogero - La Rumeur (Clip Live Officiel)",
          viewCount: "701035",
          publishedTimeText: "il y a 3 ans",
          lengthText: "3:53",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/VnMMmFinROU/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBBxpGxpJs4I91BYnXYbEvFYDdwbA",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/VnMMmFinROU/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB3YzrHhb8TmSVAMFJttOqmYWBPkA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/VnMMmFinROU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZqR2V7bNFLo7DeO9oFVK-NQju9Q",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/VnMMmFinROU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLASXNUMUaQpyNMX_NrivwSqnt89Zg",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "fHRrt_Qdx6s",
          title: "Stay Away Shows - Showreel",
          viewCount: "27372",
          publishedTimeText: "il y a 3 ans",
          lengthText: "2:36",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/fHRrt_Qdx6s/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDZX1aSH7YemJPsfdzcOb1_-Z4H-w",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/fHRrt_Qdx6s/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAFR_RzFtxF1rwxRA2yWxsTWU8wfw",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/fHRrt_Qdx6s/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCMR2fjHC1w3fgOo6CnnHSTbeTgMQ",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/fHRrt_Qdx6s/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAmZ8ak88Kvs0RyE9PquHaicB3qog",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "nr0RPVvKWDI",
          title: "Fary - Faciès | A COLORS SHOW",
          viewCount: "2184384",
          publishedTimeText: "il y a 3 ans",
          lengthText: "4:05",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/nr0RPVvKWDI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA4_cnmKKnMp4idQPnAi1Qtsv4Pbg",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/nr0RPVvKWDI/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBeTKns4gEHg9HfsKmuVLsG6wYosw",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/nr0RPVvKWDI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfWkOxsd7zVCMsE2fL1qNCt7eftg",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/nr0RPVvKWDI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDyizSH2WJNlx4h0ZIROEUKEcal_A",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "YRo4NKZHvws",
          title:
            "INSTANT LYRIQUE: 2020-2021 | ELEPHANT PANAME (live) | Google Arts & Culture",
          viewCount: "42026",
          publishedTimeText: "Diffusé il y a 3 ans",
          lengthText: "1:30:04",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/YRo4NKZHvws/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCu1gHZO7KXQp0jUZoKZXxfdNp91g",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/YRo4NKZHvws/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCiZ_4IbLBi3XeV6bWujUIGgmFKPQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/YRo4NKZHvws/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBDghU5RsQ3z2KBpMKhkjgGvPedJA",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/YRo4NKZHvws/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPjF3RSU_zEMJ7KPA-YumhNfQIBQ",
              width: 336,
              height: 188,
            },
          ],
        },
      ],
    },
    {
      type: "video_listing",
      title: "Performances Uniques",
      subtitle: null,
      data: [
        {
          type: "video",
          videoId: "T6ukF8kLGv4",
          title: "Ozuna - Ozuna Vivo | Live Album",
          viewCount: "4097779",
          publishedTimeText: "il y a 6 mois",
          lengthText: "1:39:48",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/T6ukF8kLGv4/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA5r2CDza5vahGYUz4Of8I5dMaPvA",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/T6ukF8kLGv4/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAGoqx-CfzWZW7ZKpgb9lcDeRfeUg",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/T6ukF8kLGv4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLChKcxHe-DtB77HcPRcN0R6t290Dg",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/T6ukF8kLGv4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAvCF72IKqMgcalx7Il7UhQTrFy4Q",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "IgDCPDpgiSo",
          title: "Harry Styles - As It Was (Live at The BRIT Awards 2023)",
          viewCount: "4923944",
          publishedTimeText: "il y a 6 mois",
          lengthText: "2:52",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/IgDCPDpgiSo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAC58d7Ln4TNsu4SjuM6CpjNCyoHQ",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/IgDCPDpgiSo/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLANmb8G4TkMZAOY9n4-20Jx4oTOSA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/IgDCPDpgiSo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCdnEDrd5B-itMrQzczVBowlRyxsA",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/IgDCPDpgiSo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCAJt-7VF9qwpzTGfZiKbme6TKeoA",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "6120T_EDBRc",
          title: "Wet Leg – Chaise Longue (Live at the BRIT Awards 2023)",
          viewCount: "846813",
          publishedTimeText: "il y a 6 mois",
          lengthText: "3:35",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/6120T_EDBRc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLChSWOBmA_d3VDz_12X3CUhDjD2-A",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/6120T_EDBRc/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDBnaM5K7oaMgLpFJrlKKCXDkFEbA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/6120T_EDBRc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBHbl7F4K2sDT1cgJX0cEnkoRn_yg",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/6120T_EDBRc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC51cBY1lZPeGE0koeDcmFssjCP8w",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "VbHV8oObR54",
          title: "Black Country, New Road - 'Live at Bush Hall'",
          viewCount: "565854",
          publishedTimeText: "il y a 6 mois",
          lengthText: "52:13",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/VbHV8oObR54/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCK1p_QY3riHULjrC-9qJXEoPA07A",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/VbHV8oObR54/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCYUaE2slh3MW73d8FyqS-18KYPkA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/VbHV8oObR54/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD71GGOhWSEnj-yNY2nPGEIfPZQ5A",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/VbHV8oObR54/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAnRsvRzi8oLH3gDNkltrmaVtBEkg",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "hb0XLX0b4Y4",
          title: "SKRILLEX - QUEST FOR FIRE Basement Set",
          viewCount: "5820013",
          publishedTimeText: "il y a 6 mois",
          lengthText: "23:54",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/hb0XLX0b4Y4/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCl7dolCaEcXrsBq5ZoMaH_nAzkGg",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/hb0XLX0b4Y4/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCHECawXCzcy5mq83B5pEin0JCHLQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/hb0XLX0b4Y4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBWjz1Xb95xEBnB4AUH3Y8sK7VA5g",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/hb0XLX0b4Y4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQ6RpP9e6KRob36VoMrWgPTWT-Vg",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "HjBo--1n8lI",
          title: "Rihanna’s FULL Apple Music Super Bowl LVII Halftime Show",
          viewCount: "181152213",
          publishedTimeText: "il y a 6 mois",
          lengthText: "13:51",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/HjBo--1n8lI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAe1WY454xa18HcXtzGiBHSuGzN1w",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/HjBo--1n8lI/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLC8GfGgFTbBfaFUfzmKsxhsNjJ7lA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/HjBo--1n8lI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZ65J-xx4q378ezZATllWMlVgT8w",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/HjBo--1n8lI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC_ProEyzhJVZIixC41Lttyi96Aww",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "wX0anflee0U",
          title: "The Weeknd: Live at SoFi Stadium - Die For You",
          viewCount: "2828357",
          publishedTimeText: "il y a 6 mois",
          lengthText: "4:14",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/wX0anflee0U/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDFD9BxcO7BZP87b3tZm4kKq-5qjQ",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/wX0anflee0U/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCwxug6BQ1E380LhizgfuwB65Li-Q",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/wX0anflee0U/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLByqo5lldz1qCji3QSQ0_UJguQy8w",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/wX0anflee0U/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCB4qBQM7899JaF_Wies6Xjk1vLlg",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "urV3pYW8dD4",
          title: "Paramore – Running Out of Time",
          viewCount: "736240",
          publishedTimeText: "il y a 6 mois",
          lengthText: "3:32",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/urV3pYW8dD4/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCW-_40ncyqKeqBqtBsI1RDNwWNsQ",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/urV3pYW8dD4/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCiaeYPUojRr83gX1CGP40M4AaXrA",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/urV3pYW8dD4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC1OuhZqdBCK_YwInZCCdtljEwiMg",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/urV3pYW8dD4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAufad_WfIMVEw4eimi-r4pttwqDw",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "pM9VTC6JJ8w",
          title: "NLE Choppa - Champions (Live Session) | Vevo ctrl",
          viewCount: "528993",
          publishedTimeText: "il y a 6 mois",
          lengthText: "3:44",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/pM9VTC6JJ8w/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBBRiNXDuGplZ0HF1lxDiUEYhxjfw",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/pM9VTC6JJ8w/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDiZu-7O0qU0u_jem0nyHjazHbqSQ",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/pM9VTC6JJ8w/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCblsTBdCe2-54W8gyyc2pKdfKYAA",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/pM9VTC6JJ8w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_sOdSnt_62FMlp3-x7QNv6mI9eQ",
              width: 336,
              height: 188,
            },
          ],
        },
        {
          type: "video",
          videoId: "aVsAVYDYhFI",
          title: "BABYMONSTER (#1) - HARAM (Live Performance)",
          viewCount: "15433504",
          publishedTimeText: "il y a 7 mois",
          lengthText: "2:23",
          thumbnail: [
            {
              url: "https://i.ytimg.com/vi/aVsAVYDYhFI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBNcZ0B21jrXP4SVvi3-c0zfPAH4w",
              width: 168,
              height: 94,
            },
            {
              url: "https://i.ytimg.com/vi/aVsAVYDYhFI/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBOuJ5XplaIjItqKfenJV0s01S2Ng",
              width: 196,
              height: 110,
            },
            {
              url: "https://i.ytimg.com/vi/aVsAVYDYhFI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDqL_IE3hR9W5qVGEa9mV-xZGKZ1Q",
              width: 246,
              height: 138,
            },
            {
              url: "https://i.ytimg.com/vi/aVsAVYDYhFI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCezgo5SkvbYDYGf1lLICrHCkXolg",
              width: 336,
              height: 188,
            },
          ],
        },
      ],
    },
  ],
  msg: "",
};
